### ISSUE TITLE
Feature Request: disable reading through whole file at first watch

### ISSUE THREAD

**Issue by purrcat259** [willyb321/ed-logwatcher#1]
Hi!

I'm using ed-logwatcher to watch journals for a BGS related project and it works great so far.
One feature I would like to request would be to avoid reading the whole file at startup, the reason being that I would like to also send the data as POST requests, so I don't want to send possibly thousands of lines on each startup.
I took a quick peek at the files maybe there's an undocumented setting to ignore initial read but I didn't see it.

Thanks!
Simon

**Comment by willyb321** [comment]
Yeah, I should be able to do that. I will have a poke at it later today.

**Comment by purrcat259** [comment]
Great and thanks for the prompt reply! There's no urgency at all as I have a workaround where I do not transmit the data if the array length is greater than an arbitrary number like 15, since events don't happen too frequently.

**Comment by willyb321** [comment]
I will hopefully have time to look at this today. Would you suggest an option in the constructor or an env var or something else?

**Comment by purrcat259** [comment]
I would make it a constructor variable with an appropriate default, something along the lines of ignoreInitial (default to false to preserve current behaviour too)

**Comment by willyb321** [comment]
Ok, sounds like a plan. Should be able to get to it today (if not, this week definitely)!

**Comment by purrcat259** [comment]
Great! As I had mentioned, no rush :)

**Comment by willyb321** [comment]
v1.4.0 published, let me know how it works out!

**Comment by purrcat259** [comment]
Sorry for the late reply, but thanks for this! If I find any issues I'll comment again 👍
